services:
  - type: web
    name: discord-admin-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3.11 bot.py"
    pythonVersion: "3.11.9"
